### ISSUE TITLE
Generator fails at start with default configuration

### ISSUE THREAD

**Issue by OszkarSemerath** [SNTSVV/PLEDGE#1] opened 2020-05-12 22:28 UTC
Unfortunately, the generator fails to start with the example default configurations.

We carefully followed the installation steps on the PLEDGE web site:

- We checked out the latest version of the tool from the website (https://github.com/SNTSVV/PLEDGE, Latest commit  2f166a0  on Mar 20, 2019),
- We downloaded Z3, installed it, and ensured that Z3 solver is available.
- We tried to use the attached default configurations by setting the solver.properties.
- We started the application with java -jar PLEDGE.jar
- After a few lines of logging messages, the application stopped with the following exception without actually starting the model generation:

```
2020-05-12 23:30:05,990 INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
java.lang.RuntimeException: Cannot create a resource for 'd:\Programs\PLEDGE-master/CDs/CaseA.uml'; a registered resource factory is needed
        at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:403)
        at snt.oclsolver.tuples2environment.UMLEnvironment.initUMLEnvironment(UMLEnvironment.java:455)
        at snt.oclsolver.tuples2environment.UMLEnvironment.setUpEnvironment(UMLEnvironment.java:116)
        at Main.HybridOCLSolver.main(HybridOCLSolver.java:120)
Operation not loaded UMLEnvironment!!
Exception in thread "Thread-2" java.lang.NullPointerException
        at adapters.umlImpl.EPackageUMLAdapter.getNsURI(EPackageUMLAdapter.java:163)
        at adapters.umlImpl.EResourceUMLAdapter.getContents(EResourceUMLAdapter.java:39)
        at Main.SDG.loadUmlResource(SDG.java:1312)
        at Main.SDG$PrepareEverythingHard.run(SDG.java:1600)
        at java.lang.Thread.run(Unknown Source)
Exception in thread "main" java.lang.NullPointerException
        at Main.HybridOCLSolver.main(HybridOCLSolver.java:136)

```

- We attempted to run the application on two different computers with Windows 10 operation system receiving the same error.

The exception suggests that the UML models are not loaded because they cannot be read. As a possible source of the problem, the uploaded jar file may not contain the parsers for UML models, or it fails to register the respective resource factories (which is a common Eclipse issue when a standalone Java application is compiled from an Eclipse Plugin project).

Feel free to contact me if any further details are needed.

**Comment by Ghanem-Soltana** [comment] 2020-05-12 23:20
Thank you for your feedback. So far, PLEDGE was only used and thoroughly tested over a Mac operating system. From a first glance, it appears that the issue is due to some discrepancies between how Mac and Windows operating systems deal with paths. Our team will try to recreate the exception you mentioned. The issue shall be resolved in the upcoming commit. stay tuned.

**Closed as completed** 2020-05-13 02:11 UTC
